#include "os_basic.h"

#include <vector>
#include <string>

ProcessTask Programs::CmdDogs(Proc& proc, std::vector<std::string> args)
{
	std::vector<std::string> dog_lines = 
	{
		ESC "[2J",
		ESC "[1;25H          __ ",
		ESC "[2;25H        _/ o\\__,",
		ESC "[3;25H       /   ____/",
		ESC "[4;25H      /   /",
		ESC "[5;25H    _-   /\\\\   __",
		ESC "[6;25H \\_/   /---\\\\-/ o\\__",
		ESC "[7;25H    \\ |=  ___  ____/  ",
		ESC "[8;25H    | /| /   ||",
		ESC "[9;25H    ||_||    ||_",
		ESC "[10;25H ~~~~~~~~~~~~~~~~~~~~~~~~~",
		ESC "[20;25H                                                          ",
		ESC "[20;25H                                                          ",
		ESC "[20;25H                                                          ",
		ESC "[2;25H        _/ -\\__",
		ESC "[5;25H     /   /\\\\   __",
		ESC "[6;25H  \\_/   /--\\\\-/ O\\__ ",
		ESC "[7;25H    |  /  ___  ____/  ",
		ESC "[20;25H                                                          ",
		ESC "[20;25H                                                        ",
		ESC "[20;25H                                                          ",
		ESC "[5;25H    _-   /\\\\   __",
		ESC "[6;25H  _/   /---\\\\-/ o\\__",
		ESC "[7;25H /  \\ |=  ___  ____/  ",
		ESC "[20;25H                                                          ",
		ESC "[20;25H                                                        ",
		ESC "[20;25H                                                          ",
		ESC "[5;25H     /   /\\\\   __",
		ESC "[6;25H  \\_/   /--\\\\-/ O\\__ ",
		ESC "[7;25H    |  /  ___  ____/  ",
		ESC "[20;25H                                                          ",
		ESC "[20;25H                                                        ",
		ESC "[20;25H                                                          ",
		ESC "[5;25H    _-   /\\\\   __",
		ESC "[6;25H  _/   /---\\\\-/ o\\__",
		ESC "[7;25H /  \\ |=  ___  ____/  ",
		ESC "[20;25H                                                          ",
		ESC "[20;25H                                                        ",
		ESC "[20;25H                                                          ",
		ESC "[5;25H     /   /\\\\   __",
		ESC "[6;25H  \\_/   /--\\\\-/ O\\__ ",
		ESC "[7;25H    |  /  ___  ____/  ",
		ESC "[20;25H                                                          ",
		ESC "[20;25H                                                        ",
		ESC "[20;25H                                                          ",
		ESC "[5;25H    _-   /\\\\   __",
		ESC "[6;25H  _/   /---\\\\-/ o\\__",
		ESC "[7;25H /  \\ |=  ___  ____/  ",
		ESC "[20;25H                                                          ",
		ESC "[20;25H                                                        ",
		ESC "[20;25H                                                          ",
		ESC "[5;25H     /   /\\\\   __",
		ESC "[6;25H  \\_/   /--\\\\-/ O\\__ ",
		ESC "[7;25H    |  /  ___  ____/  ",
		ESC "[20;25H                                                          ",
		ESC "[20;25H                                                        ",
		ESC "[20;25H                                                          ",
		ESC "[5;25H    _-   /\\\\   __",
		ESC "[6;25H  _/   /---\\\\-/ o\\__",
		ESC "[7;25H /  \\ |=  ___  ____/  ",
		ESC "[20;25H                                                          ",
		ESC "[20;25H                                                        ",
		ESC "[20;25H                                                          ",
		ESC "[5;25H     /   /\\\\   __",
		ESC "[6;25H  \\_/   /--\\\\-/ O\\__ ",
		ESC "[7;25H    |  /  ___  ____/  ",
		ESC "[20;25H                                                          ",
		ESC "[20;25H                                                        ",
		ESC "[20;25H                                                          ",
		ESC "[5;25H    _-   /\\\\   __",
		ESC "[6;25H  _/   /---\\\\-/ o\\__",
		ESC "[7;25H /  \\ |=  ___  ____/  ",
		ESC "[20;25H                                                          ",
		ESC "[20;25H                                                        ",
		ESC "[20;25H                                                          ",
		ESC "[5;25H     /   /\\\\   __",
		ESC "[6;25H  \\_/   /--\\\\-/ O\\__ ",
		ESC "[7;25H    |  /  ___  ____/  ",
		ESC "[20;25H                                                          ",
		ESC "[20;25H                                                        ",
		ESC "[20;25H                                                          ",
		ESC "[5;25H    _-   /\\\\   __",
		ESC "[6;25H  _/   /---\\\\-/ o\\__",
		ESC "[7;25H /  \\ |=  ___  ____/  ",
		ESC "[20;25H                                                          ",
		ESC "[20;25H                                                        ",
		ESC "[20;25H                                                          ",
		ESC "[5;25H     /   /\\\\   __",
		ESC "[6;25H  \\_/   /--\\\\-/ O\\__ ",
		ESC "[7;25H    |  /  ___  ____/  ",
		ESC "[20;25H                                                          ",
		ESC "[20;25H                                                        ",
		ESC "[20;25H                                                          ",
		ESC "[5;25H    _-   /\\\\   __",
		ESC "[6;25H  _/   /---\\\\-/ o\\__",
		ESC "[7;25H /  \\ |=  ___  ____/  ",
		ESC "[20;25H                                                          ",
		ESC "[20;25H                                                        ",
		ESC "[20;25H                                                          ",
		ESC "[5;25H     /   /\\\\   __",
		ESC "[6;25H  \\_/   /--\\\\-/ O\\__ ",
		ESC "[7;25H    |  /  ___  ____/  ",
		ESC "[20;25H                                                          ",
		ESC "[20;25H                                                        ",
		ESC "[20;25H                                                          ",
		ESC "[5;25H    _-   /\\\\   __",
		ESC "[6;25H  _/   /---\\\\-/ o\\__",
		ESC "[7;25H /  \\ |=  ___  ____/  ",
		ESC "[20;25H                                                          ",
		ESC "[20;25H                                                        ",
		ESC "[20;25H                                                          ",
		ESC "[5;25H     /   /\\\\   __",
		ESC "[6;25H  \\_/   /--\\\\-/ O\\__ ",
		ESC "[7;25H    |  /  ___  ____/  ",
		ESC "[20;25H                                                          ",
		ESC "[20;25H                                                        ",
		ESC "[20;25H                                                          ",
		ESC "[5;25H    _-   /\\\\   __",
		ESC "[6;25H  _/   /---\\\\-/ o\\__",
		ESC "[7;25H /  \\ |=  ___  ____/  ",
		ESC "[20;25H                                                          ",
		ESC "[20;25H                                                        ",
		ESC "[20;25H                                                          ",
		ESC "[5;25H     /   /\\\\   __",
		ESC "[6;25H  \\_/   /--\\\\-/ O\\__ ",
		ESC "[7;25H    |  /  ___  ____/  ",
		ESC "[20;25H                                                          ",
		ESC "[20;25H                                                        ",
		ESC "[20;25H                                                          ",
		ESC "[5;25H    _-   /\\\\   __",
		ESC "[6;25H  _/   /---\\\\-/ o\\__",
		ESC "[7;25H /  \\ |=  ___  ____/  ",
		ESC "[20;25H                                                          ",
		ESC "[20;25H                                                        ",
		ESC "[20;25H                                                          ",
		ESC "[20;25H                                                          ",
		ESC "[20;25H                                                        ",
		ESC "[20;25H                                                          ",
		ESC "[20;25H                                                          ",
		ESC "[20;25H                                                        ",
		ESC "[20;25H                   ",
		ESC "[2;25H        _/ .\\__,  Arrrgh",
		ESC "[3;25H       /   ____/    _/",
		ESC "[4;25H      /   /",
		ESC "[5;25H     /   /\\\\   __   ",
		ESC "[6;25H  \\_/   /--\\\\-/ *\\__  Woof.",
		ESC "[7;25H    |  /  ___  ____/  _/ ",
		ESC "[21;25H",
		ESC "[6;25H  \\",
		ESC "[7;25H   ",
		ESC "[20;25H                                                        ",
		ESC "[6;25H   ",
		ESC "[7;25H  /",
		ESC "[6;25H  \\",
		ESC "[7;25H   ",
		ESC "[20;25H                                                        ",
		ESC "[6;25H   ",
		ESC "[7;25H  /",
		ESC "[6;25H  \\",
		ESC "[7;25H   ",
		ESC "[20;25H                                                        ",
		ESC "[6;25H   ",
		ESC "[7;25H  /",
		ESC "[6;25H  \\",
		ESC "[7;25H   ",
		ESC "[20;25H                                                        ",
		ESC "[6;25H   ",
		ESC "[7;25H  /",
		ESC "[6;25H  \\",
		ESC "[7;25H   ",
		ESC "[20;25H                                                        ",
		ESC "[6;25H   ",
		ESC "[7;25H  /",
		ESC "[6;25H  \\",
		ESC "[7;25H   ",
		ESC "[20;25H                                                        ",
		ESC "[6;25H   ",
		ESC "[7;25H  /",
		ESC "[6;25H  \\",
		ESC "[7;25H   ",
		ESC "[20;25H                                                        ",
		ESC "[6;25H   ",
		ESC "[7;25H  /",
		ESC "[6;25H  \\",
		ESC "[7;25H   ",
		ESC "[20;25H                                                        ",
		ESC "[6;25H   ",
		ESC "[7;25H  /",
		ESC "[6;25H  \\",
		ESC "[7;25H   ",
		ESC "[20;25H                                                        ",
		ESC "[6;25H   ",
		ESC "[7;25H  /",
		ESC "[6;25H  \\",
		ESC "[7;25H   ",
		ESC "[20;25H                                                        ",
		ESC "[6;25H   ",
		ESC "[7;25H  /",
		ESC "[6;25H  \\",
		ESC "[7;25H   ",
		ESC "[20;25H                                                        ",
		ESC "[6;25H   ",
		ESC "[7;25H  /",
		ESC "[6;25H  \\",
		ESC "[7;25H   ",
		ESC "[20;25H                                                        ",
		ESC "[6;25H   ",
		ESC "[7;25H  /",
		ESC "[6;25H  \\",
		ESC "[7;25H   ",
		ESC "[20;25H                                                        ",
		ESC "[6;25H   ",
		ESC "[7;25H  /",
		ESC "[6;25H  \\",
		ESC "[7;25H   ",
		ESC "[20;25H                                                        ",
		ESC "[6;25H   ",
		ESC "[7;25H  /",
		ESC "[6;25H  \\",
		ESC "[7;25H   ",
		ESC "[20;25H                                                        ",
		ESC "[6;25H   ",
		ESC "[7;25H  /",
		ESC "[6;25H  \\",
		ESC "[7;25H   ",
		ESC "[20;25H                                                        ",
		ESC "[6;25H   ",
		ESC "[7;25H  /",
		ESC "[6;25H  \\",
		ESC "[7;25H   ",
		ESC "[20;25H                                                        ",
		ESC "[6;25H   ",
		ESC "[7;25H  /",
		ESC "[6;25H  \\",
		ESC "[7;25H   ",
		ESC "[20;25H                                                        ",
		ESC "[6;25H   ",
		ESC "[7;25H  /",
		ESC "[6;25H  \\",
		ESC "[7;25H   ",
		ESC "[20;25H                                                        ",
		ESC "[6;25H   ",
		ESC "[7;25H  /",
		ESC "[6;25H  \\",
		ESC "[7;25H   ",
		ESC "[20;25H                                                        ",
		ESC "[6;25H   ",
		ESC "[7;25H  /",
		ESC "[21;25H"
	};

	OS& os = *proc.owning_os;

	int32_t width = proc.get_var<int32_t>("TERM_W");
	int32_t height = proc.get_var<int32_t>("TERM_H");

	if (width == 0 || height == 0)
	{
		proc.warnln("The terminal width/height parameter needs to be set for dogs.");
		co_return 1;
	}

	com::CommandReply begin_msg;
	begin_msg.set_reply(
		BEGIN_ALT_SCREEN_BUFFER 
		CLEAR_CURSOR 
		CLEAR_SCREEN
		HIDE_CURSOR);

	proc.write(begin_msg);
	
	for (const std::string& line : dog_lines)
	{
		co_await os.wait(0.1f);
		proc.put("{}", line);
	}

	com::CommandReply end_msg;
	end_msg.set_reply(
		END_ALT_SCREEN_BUFFER
		SHOW_CURSOR 
		"Dogs finished...\n");

	proc.write(end_msg);

	co_return 0;
}